Load entities and policies from json file
permitio/cedar-agent pull request #12
Opened 2023-07-17 19:38 UTC by cleissonbarbosa

**Reason**: Unable to load a large amount of entities (30,000 - 4.5MB) from the `/data` endpoint

**What PR does**: Adds the possibility to load entities and policies from a json file at rocket startup

Use the `-d` or `--data` option and inform the path of the json file you want to load in cedar's memory, it is also possible to use a `DATA` environment variable

examples:

```bash
cargo run -- -d "./examples/data.json"
```

```bash
cargo run -- --data="./examples/data.json"
```

```bash
export DATA="./examples/data.json"
cargo run
```
---

Use the  `--policy` option and inform the path of the json file you want to load in cedar's memory, it is also possible to use a `POLICY` environment variable

examples:

```bash
cargo run -- --policy="./examples/policies.json"
```

```bash
export POLICY="./examples/policies.json"
cargo run
```

2023-07-18 10:01 UTC, omer9564 requested changes
Looks good in general, the only major changes needed here is missing tests

2023-07-18 10:01 UTC, omer9564 commented on README.md
> +  `--data`, `-d` command line argument.
missing policy file configuration

2023-07-18 12:18 UTC, cleissonbarbosa commented
@omer9564 Thank you very much for the review, in addition to the changes you requested, I changed the word policy to policies in the config.

2023-07-18 13:12 UTC, omer9564 requested changes
two suggestion comments ( might make the code simpler )
one missing new line again 😅 , Besides that it looks great 💪

2023-07-18 13:12 UTC, omer9564 commented on tests/services/data_tests.rs
> +    let temp_file_path = Arc::new(PathBuf::from("test_entities.json"));
you could also use the data.json from the examples directory

2023-07-18 13:12 UTC, omer9564 commented on tests/services/data_tests.rs
> +}
missing new line at end of file

2023-07-18 13:12 UTC, omer9564 commented on tests/services/policies_tests.rs
> +    let temp_file_path = Arc::new(PathBuf::from("test_policies.json"));
you could also use the policies.json from the examples directory

2023-07-18 13:34 UTC, cleissonbarbosa commented
> two suggestion comments ( might make the code simpler ) one missing new line again 😅 , Besides that it looks great 💪

😅 thank you very much for the suggestion.

2023-07-18 13:54 UTC, danielbass37 commented
@cleissonbarbosa PMed you in the community <3

2023-07-18 14:09 UTC, cleissonbarbosa commented
@orweis @danielbass37 Thank you guys 💜

2023-07-20 07:59 UTC, omer9564 approved these changes
LGTM

2023-08-15 13:25 UTC, merged